export const countryData = [
  "China",
  "United States",
  "India",
  "Brazil",
  "Russia",
  "Canada",
  "Australia",
  "France",
  "Germany",
  "Japan",
  "Mexico",
  "South Korea",
  "Italy",
  "United Kingdom",
  "Turkey",
  "Spain",
  "Indonesia",
  "Saudi Arabia",
  "South Africa",
  "Argentina",
  "Morocco",
  "Egypt",
  "Nigeria",
  "Kenya",
];

export const cityData = {
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hangzhou",
    "Ningbo",
    "Wenzhou",
    "Nanjing",
    "Suzhou",
    "Zhenjiang",
    "Chongqing",
    "Tianjin",
    "Xi'an",
    "Changsha",
    "Qingdao",
    "Dalian",
    "Shenyang",
    "Harbin",
    "Zhengzhou",
    "Jinan",
    "Kunming",
    "Xiamen",
    "Fuzhou",
    "Dongguan",
    "Nanning",
    "Urumqi",
    "Lanzhou",
    "Yinchuan",
    "Guiyang",
    "Hohhot",
    "Shijiazhuang",
    "Taiyuan",
    "Hefei",
    "Nanchang",
    "Changchun",
    "Shijiazhuang",
    "Yantai",
    "Foshan",
    "Wuhan",
    "Shenyang",
    "Suzhou",
    "Ningbo",
    "Zhuhai",
  ],
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Long Beach",
    "Mesa",
    "Atlanta",
    "Colorado Springs",
  ],
  India: [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Allahabad",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
  ],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Goiânia",
    "Belém",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "São Gonçalo",
    "Maceió",
    "Duque de Caxias",
    "Natal",
    "Teresina",
    "Nova Iguaçu",
    "Campo Grande",
    "João Pessoa",
    "Santo André",
    "Jaboatão dos Guararapes",
    "Osasco",
    "São Bernardo do Campo",
    "Contagem",
    "Ribeirão Preto",
    "Uberlândia",
  ],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Perm",
    "Voronezh",
    "Volgograd",
    "Krasnodar",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Ulyanovsk",
    "Irkutsk",
    "Khabarovsk",
    "Yaroslavl",
    "Vladivostok",
    "Makhachkala",
    "Tomsk",
    "Orenburg",
    "Kemerovo",
  ],
  Canada: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
    "Saskatoon",
    "Regina",
    "St. John's",
    "Sudbury",
    "Chicoutimi",
    "Sherbrooke",
    "Kelowna",
    "Abbotsford",
    "Kingston",
    "Barrie",
    "Guelph",
    "Moncton",
    "Brantford",
    "Thunder Bay",
    "Red Deer",
  ],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Wollongong",
    "Logan City",
    "Geelong",
    "Hobart",
    "Townsville",
    "Cairns",
    "Darwin",
    "Toowoomba",
    "Ballarat",
    "Bendigo",
    "Launceston",
    "Albury",
    "Mackay",
    "Rockhampton",
    "Bunbury",
    "Bundaberg",
    "Coffs Harbour",
    "Wagga Wagga",
    "Hervey Bay",
    "Mildura",
    "Port Macquarie",
    "Tamworth",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Clermont-Ferrand",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Boulogne-Billancourt",
    "Perpignan",
  ],
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
  ],
  Japan: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Kitakyushu",
    "Chiba",
    "Sakai",
    "Niigata",
    "Hamamatsu",
    "Shizuoka",
    "Sagamihara",
    "Okayama",
    "Kumamoto",
    "Kagoshima",
    "Funabashi",
    "Hachioji",
    "Matsuyama",
    "Kanazawa",
    "Utsunomiya",
    "Oita",
    "Nagasaki",
    "Miyazaki",
  ],
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Toluca",
    "Tijuana",
    "León",
    "Ciudad Juárez",
    "Torreón",
    "Querétaro",
    "Chihuahua",
    "Mérida",
    "San Luis Potosí",
    "Aguascalientes",
    "Hermosillo",
    "Saltillo",
    "Morelia",
    "Culiacán",
    "Veracruz",
    "Villahermosa",
    "Cancún",
    "Reynosa",
    "Oaxaca",
    "Tuxtla Gutiérrez",
    "Durango",
    "Acapulco",
    "Tampico",
    "Mazatlán",
    "Celaya",
    "Colima",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Ansan",
    "Cheongju",
    "Jeonju",
    "Cheonan",
    "Gimhae",
    "Pohang",
    "Jinju",
    "Gangneung",
    "Yeosu",
    "Suncheon",
    "Gunsan",
    "Gwangmyeong",
    "Iksan",
    "Uijeongbu",
    "Hwaseong",
    "Gumi",
    "Andong",
  ],
  Italy: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Catania",
    "Bari",
    "Venice",
    "Verona",
    "Messina",
    "Padua",
    "Trieste",
    "Taranto",
    "Brescia",
    "Parma",
    "Prato",
    "Modena",
    "Reggio Calabria",
    "Reggio Emilia",
    "Perugia",
    "Livorno",
    "Ravenna",
    "Foggia",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Latina",
  ],
  "United Kingdom": [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Newcastle",
    "Liverpool",
    "Leeds",
    "Sheffield",
    "Edinburgh",
    "Bristol",
    "Leicester",
    "Coventry",
    "Nottingham",
    "Hull",
    "Cardiff",
    "Belfast",
    "Stoke-on-Trent",
    "Reading",
    "Southampton",
    "Derby",
    "Plymouth",
    "Luton",
    "Aberdeen",
    "Norwich",
    "Swansea",
    "Milton Keynes",
    "Oxford",
    "Slough",
    "Cambridge",
    "York",
  ],
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Antalya",
    "Adana",
    "Gaziantep",
    "Konya",
    "Kayseri",
    "Mersin",
    "Eskişehir",
    "Diyarbakır",
    "Samsun",
    "Denizli",
    "Şanlıurfa",
    "Malatya",
    "Kahramanmaraş",
    "Erzurum",
    "Sivas",
    "İzmit",
    "Batman",
    "Elazığ",
    "Aydın",
    "Trabzon",
    "Çorum",
    "Mardin",
    "Van",
    "Kütahya",
    "Muş",
    "Kırıkkale",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Cordoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Eixample",
    "L'Hospitalet de Llobregat",
    "Vitoria-Gasteiz",
    "A Coruña",
    "Granada",
    "Elche",
    "Oviedo",
    "Santa Cruz de Tenerife",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez de la Frontera",
    "Sabadell",
    "Móstoles",
    "Alcalá de Henares",
  ],
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Bekasi",
    "Medan",
    "Tangerang",
    "Depok",
    "Semarang",
    "Palembang",
    "Makassar",
    "South Tangerang",
    "Batam",
    "Pekanbaru",
    "Bogor",
    "Padang",
    "Denpasar",
    "Malang",
    "Samarinda",
    "Tasikmalaya",
    "Serang",
    "Banjarmasin",
    "Balikpapan",
    "Jambi",
    "Mataram",
    "Cirebon",
    "Manado",
    "Ambon",
    "Kupang",
    "Bengkulu",
    "Palu",
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Khobar",
    "Tabuk",
    "Abha",
    "Khamis Mushait",
    "Hail",
    "Najran",
    "Jizan",
    "Al Bahah",
    "Al Jawf",
    "Al Kharj",
    "Arar",
    "Sakaka",
    "Rafha",
    "Al Ula",
    "Sharurah",
    "Dhahran",
    "Al Qatif",
    "Al Jubail",
    "Bisha",
    "Al Majma'ah",
    "Al Khafji",
    "Hafar Al-Batin",
    "Al Qurayyat",
    "Al Bada'a",
    "Al Lith",
  ],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "Nelspruit",
    "Kimberley",
    "Polokwane",
    "East London",
    "Pietermaritzburg",
    "Welkom",
    "Uitenhage",
    "Vereeniging",
    "Benoni",
    "Tembisa",
    "Katlehong",
    "Soweto",
    "Soshanguve",
    "Middelburg",
    "Mthatha",
    "Rustenburg",
    "Phalaborwa",
    "Witbank",
    "Klerksdorp",
    "Potchefstroom",
    "Queenstown",
    "Thohoyandou",
    "Bethlehem",
    "Mokopane",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "San Miguel de Tucumán",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Neuquén",
    "Santiago del Estero",
    "Corrientes",
    "Posadas",
    "San Salvador de Jujuy",
    "Bahía Blanca",
    "Paraná",
    "Trelew",
    "Comodoro Rivadavia",
    "Formosa",
    "San Fernando del Valle de Catamarca",
    "La Rioja",
    "San Luis",
    "Río Gallegos",
    "Río Cuarto",
    "General Roca",
    "Río Tercero",
    "Rafaela",
    "Villa María",
  ],
  Morocco: [
    "Casablanca",
    "Rabat",
    "Marrakesh",
    "Fes",
    "Tangier",
    "Agadir",
    "Meknes",
    "Oujda",
    "Kenitra",
    "Tetouan",
    "Safi",
    "Khouribga",
    "Beni Mellal",
    "Mohammedia",
    "El Jadida",
    "Taza",
    "Nador",
    "Settat",
    "Larache",
    "Khemisset",
    "Ouarzazate",
    "Guelmim",
    "Berkane",
    "Ksar El Kebir",
    "Bouskoura",
    "Inezgane",
    "Sidi Slimane",
    "Dakhla",
    "Errachidia",
    "Sidi Ifni",
  ],
  Egypt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "al-Mansura",
    "El-Mahalla El-Kubra",
    "Tanta",
    "Asyut",
    "Ismailia",
    "Fayoum",
    "Zagazig",
    "Damietta",
    "Aswan",
    "Minya",
    "Damanhur",
    "Beni Suef",
    "Qena",
    "Sohag",
    "Hurghada",
    "6th of October City",
    "Sharm El Sheikh",
    "Banha",
    "Kafr El Sheikh",
    "Beni Mazar",
    "Malawi",
    "Qus",
    "Biba",
  ],
  Nigeria: [
    "Lagos",
    "Kano",
    "Ibadan",
    "Benin City",
    "Port Harcourt",
    "Jos",
    "Ilorin",
    "Enugu",
    "Maiduguri",
    "Zaria",
    "Aba",
    "Ogbomosho",
    "Onitsha",
    "Warri",
    "Sokoto",
    "Okene",
    "Calabar",
    "Uyo",
    "Abuja",
    "Kaduna",
    "Owerri",
    "Ado Ekiti",
    "Akure",
    "Minna",
    "Makurdi",
    "Gombe",
    "Damaturu",
    "Lokoja",
    "Jalingo",
    "Gusau",
  ],
  Kenya: [
    "Nairobi",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Thika",
    "Nyeri",
    "Meru",
    "Machakos",
    "Ruiru",
    "Kakamega",
    "Kitale",
    "Garissa",
    "Bungoma",
    "Busia",
    "Malindi",
    "Isiolo",
    "Nanyuki",
    "Kiambu",
    "Embu",
    "Naivasha",
    "Kericho",
    "Kilifi",
    "Wajir",
    "Marsabit",
    "Lamu",
  ],
};
